CHANNELS_URL = {
    "TF1": "https://www.tf1.fr/tf1/direct",
    "France 2": "https://www.france.tv/france-2/direct.html",
    "France 3": "https://www.france.tv/france-3/direct.html",
    "F3 Alpes": "https://www.france.tv/france-3/alpes/direct.html",
    "F3 Alsace": "https://www.france.tv/france-3/alsace/direct.html",
    "F3 Aquitaine": "https://www.france.tv/france-3/aquitaine/direct.html",
    "F3 Auvergne": "https://www.france.tv/france-3/auvergne/direct.html",
    "F3 Basse-Normandie": "https://www.france.tv/france-3-basse-normandie/direct.html",
    "F3 Bourgogne": "https://www.france.tv/france-3/bourgogne/direct.html",
    "F3 Bretagne": "https://www.france.tv/france-3/bretagne/direct.html",
    "F3 Centre-Val de Loire": "https://www.france.tv/france-3/centre-val-de-loire/direct.html",
    "F3 Champagne-Ardennes": "https://www.france.tv/france-3/champagne-ardenne/direct.html",
    "F3 Corse Via Stella": "https://www.france.tv/france-3/corse-via-stella/direct.html",
    "F3 Côte-d'Azur": "https://www.france.tv/france-3/cote-d-azur/direct.html",
    "F3 Franche-Comte": "https://www.france.tv/france-3/franche-comte/direct.html",
    "F3 Haute-Normandie": "https://www.france.tv/france-3/haute-normandie/direct.html",
    "F3 Languedoc-Roussillon": "https://www.france.tv/france-3/languedoc-roussillon/direct.html",
    "F3 Limousin": "https://www.france.tv/france-3/limousin/direct.html",
    "F3 Lorraine": "https://www.france.tv/france-3/lorraine/direct.html",
    "F3 Midi-Pyrénées": "https://www.france.tv/france-3/midi-pyrenees/direct.html",
    "F3 Nord Pas-de-Calais": "https://www.france.tv/france-3/nord-pas-de-calais/direct.html",
    "F3 Paris Île-de-France": "https://www.france.tv/france-3/paris-ile-de-france/direct.html",
    "F3 Pays de la Loire": "https://www.france.tv/france-3/pays-de-la-loire/direct.html",
    "F3 Picardie": "https://www.france.tv/france-3/picardie/direct.html",
    "F3 Poitou-Charentes": "https://www.france.tv/france-3/poitou-charentes/direct.html",
    "F3 Provence-Alpes": "https://www.france.tv/france-3/provence-alpes/direct.html",
    "F3 Rhône-Alpes": "https://www.france.tv/france-3/rhone-alpes/direct.html",
    "France 4": "https://www.france.tv/france-4/direct.html",
    "France 5": "https://www.france.tv/france-5/direct.html",
    "Arte": "https://www.arte.tv/fr/direct",
    "TMC": "https://www.tf1.fr/tmc/direct",
    "TFX": "https://www.tf1.fr/tfx/direct",
    "BFM TV": "https://www.bfmtv.com/en-direct",
    "CNEWS": "https://www.dailymotion.com/video/x3b68jn",
    "LCI": "https://www.tf1.fr/lci/direct",
    "franceinfo": "https://www.france.tv/franceinfo/direct.html",
    "CSTAR": "https://www.dailymotion.com/video/x5gv5v0",
    "TF1 Séries Films": "https://www.tf1.fr/tf1-series-films/direct",
    "L'Equipe": "https://www.tf1.fr/l-equipe/direct",
    "LCP": "https://www.dailymotion.com/video/xgepjr",
    "PUBLIC SENAT 2424": "https://www.dailymotion.com/video/xkxbzc",
}
